### ISSUE TITLE
Feature: User can create an account

### ISSUE THREAD

**Issue by Daniel-J-Cho** [Daniel-J-Cho/Driving-Game#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create a new account

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can create a new account by clicking the "Create an account" button on the top right of the home page.
A modal will appear with "Create username" and "Create password" inputs.  Once account is created, user is taken to first page of instructions.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

Mobile
![image](https://github.com/Daniel-J-Cho/Driving-Game/assets/20695764/7c47ee27-e797-4ade-8fbf-3ea5c1960b88)
![image](https://github.com/Daniel-J-Cho/Driving-Game/assets/20695764/0546309d-687d-4340-931f-f1e69152aa07)
![image](https://github.com/Daniel-J-Cho/Driving-Game/assets/20695764/72c738ac-0137-48cf-b3a1-a0daa7868f98)

Desktop
![image](https://github.com/Daniel-J-Cho/Driving-Game/assets/20695764/06ca3a81-c98f-47b0-a181-061327f884c3)
![image](https://github.com/Daniel-J-Cho/Driving-Game/assets/20695764/78166acd-c5ba-4f65-90e5-4a4c0302816f)
![image](https://github.com/Daniel-J-Cho/Driving-Game/assets/20695764/fd9773e6-a7aa-44b5-9e7e-83cdf1d57f69)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Update `schema.sql` to create table for users that store usernames and passwords
- [ ] Update `data.sql` to contain data for `guest` user and password for users that just want to play without creating username and password

### ☁️ Server Tasks

- [ ] Update `server.js` to ...
- [ ] Test with HTTPie
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a component that represents and positions a car
- [ ] Create a component to create 'Click here to start' button
- [ ] Create a component to create and position 'Sign In' button
- [ ] Create a component to create and position 'Create an account' button
- [ ] Create a component that creates a 'Create an account' modal
- [ ] Update component to make 'Click here to start' button functional so that clicking it takes user to first step of instructions
- [ ] Update component to make 'Create an account' button functional so that clicking it makes the 'Create an account' modal appear

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
